databases:
  - name: app-auditoria-db
    databaseName: diabetes_db
    user: root
    plan: free

services:
  - type: web
    name: app-auditoria
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    startCommand: cd backend && npx prisma db push --skip-generate && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        fromDatabase:
          name: app-auditoria-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
